# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KafkaConnectCli < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lala7573/kafka-connect-cli/releases/download/v0.1.1/kafka-connect-cli_0.1.1_Darwin_arm64.tar.gz"
      sha256 "d132a890b4cc3b7925d8c2613323cec7e788f58ff65af74cebc44a0dbbe3800d"

      def install
        bin.install "kafka-connect-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lala7573/kafka-connect-cli/releases/download/v0.1.1/kafka-connect-cli_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "3fa71f7e23dea4703ed79991a1f941f5d49bc7892ddcc04386ceca7ce6c98e49"

      def install
        bin.install "kafka-connect-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lala7573/kafka-connect-cli/releases/download/v0.1.1/kafka-connect-cli_0.1.1_Linux_arm64.tar.gz"
      sha256 "d6f30ef6fcfb4e5c8a7d92b1f47a7ae4c647c994cfeb3cc9631d04dd3b7ef148"

      def install
        bin.install "kafka-connect-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lala7573/kafka-connect-cli/releases/download/v0.1.1/kafka-connect-cli_0.1.1_Linux_x86_64.tar.gz"
      sha256 "d7b6ed6cd59978f4ad9c11fa8c32b3c6799a5dd13074088d3026a56b371c29d1"

      def install
        bin.install "kafka-connect-cli"
      end
    end
  end
end
