# This file was generated by GoReleaser. DO NOT EDIT.
class KafkaConnectCli < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lala7573/kafka-connect-cli/releases/download/v0.1.0/kafka-connect-cli_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "f9a5b48905f08f0cfa7325666400a6447d693fb7172e91d25aed33c9e04f80b0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/lala7573/kafka-connect-cli/releases/download/v0.1.0/kafka-connect-cli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "0d0c9ad25efd38e4f935ebb42fbb29c9adc2927f74d4763249fb4e298aebd7f9"
    end
  end

  def install
    bin.install "kafka-connect-cli"
  end
end
